#ifndef __APP_CONFIG_H
#define __APP_CONFIG_H

#define ADC_MAX_VALUE        4095
#define ADC_REF_MV           3300
#define ADC_FILTER_SAMPLE_COUNT  16
#define ALARM_THRESHOLD_MV   2400
#define ALARM_HYSTERESIS_MV  50
#define MOTOR_ALARM_SPEED    100
#define MOTOR_STOP_SPEED     0
#define APP_LOOP_PERIOD_MS   50
#define STATUS_REPORT_INTERVAL_TICKS  20
#define ALARM_WARNING_INTERVAL_TICKS  20

#endif
